import { fileURLToPath } from 'node:url';

import type { NextConfig } from 'next';

/**
 * The public informational site is **statically renderable and has no request-time
 * dependency on anything**, and that is the fence rather than a preference.
 *
 * MCS-34 describes this surface by four negatives — public, unauthenticated, no
 * personal data, no API dependency at request time — and the last one is the
 * interesting one: `www.mageride.lk` must render with the entire platform down.
 * There is therefore no gateway origin here, no `NEXT_PUBLIC_*` variable to inline
 * and nothing in this file that points at the platform.
 *
 * Four settings carry a decision:
 *
 *   - `output: 'standalone'` because the deployment target is a container
 *     (D6, `infra/docker/Dockerfile.portal`) rather than a Node tree with
 *     `node_modules` beside it.
 *   - `outputFileTracingRoot` because that Dockerfile asserts
 *     `.next/standalone/portals/<portal>/server.js`. Left alone, Next roots the
 *     trace at the nearest lockfile — `portals/` — and emits one segment less. The
 *     failure is a build that succeeds and a container with no server to start.
 *   - `poweredByHeader: false`. Nothing on a marketing page needs to announce which
 *     framework rendered it.
 *   - `images.formats` puts AVIF ahead of WebP. Phase 3 commits ~70 composited
 *     device frames into `public/screens/` and the performance budget (A34) is
 *     written against a 3G-throttled mid-range Android; AVIF is the format that
 *     budget assumes.
 *
 * There is deliberately **no `tailwind.config.js`** — not here and not as a
 * sibling file. Tailwind v4 reads its theme from CSS
 * (`app/globals.css` → `@mageride/tailwind-preset/theme.css`), and a JS config on
 * v4 *merges* `screens` instead of replacing them, which would quietly restore
 * Tailwind's 640px `sm:` over D2's 375px one (`portals/tailwind-preset/README.md`).
 * D8 caps this surface at `max-w-[1200px]` and keeps D2's three widths, so there is
 * no breakpoint on this site that the preset does not already carry.
 *
 * **Cache headers arrived in S21**, and they are `headers()` below rather than ingress
 * annotations — which reverses what S03 assumed and is worth the paragraph.
 *
 * The reasoning that put them at the edge was that caching is a deployment concern (A44)
 * and belongs beside the apex 301. What that misses is *which* responses need which
 * policy: `/_next/static/**` is content-hashed and immutable, `/screens/**` is committed
 * and effectively immutable, and an HTML page is neither. Expressing that at the ingress
 * means an nginx `location` regex per class, maintained in a different repository layer
 * from the routes it describes, and drifting the first time a path moves. Next already
 * knows which response it is serving.
 *
 * The edge keeps what is genuinely the edge's: TLS, HSTS, the apex 301 (S21 §4). An
 * ingress that also decided cache lifetimes would be the second place a path is named.
 */
/**
 * One year, immutable — for responses whose URL changes when their bytes do.
 *
 * `immutable` tells a browser not to revalidate even on a reload, which is only safe when
 * the URL is a function of the content. Both classes below satisfy that:
 * `/_next/static/**` is content-hashed by the build, and `/screens/**` is generated by
 * `npm run screens:refresh` and committed — a changed image is a changed file that a
 * changed page references.
 */
const IMMUTABLE = 'public, max-age=31536000, immutable';

/**
 * HTML: five minutes at the edge, a day of stale-while-revalidate behind it.
 *
 * **`stale-while-revalidate` is the fence extended one layer out**, and it is the reason
 * this value is not simply "short". MCS-34's fourth negative is that this surface renders
 * with the entire platform down; `s-maxage=300, stale-while-revalidate=86400` says that a
 * cache which cannot reach the origin should keep serving the page it has for a day while
 * it retries. So the site survives the *cluster* being down as well as the platform — a
 * marketing page that is up during an outage is worth more than one that is five minutes
 * fresher.
 *
 * `s-maxage` and not `max-age`: the shared cache holds the copy, the reader's browser
 * revalidates. A marketing page corrected at 09:00 should not be stale in somebody's tab
 * until tomorrow.
 */
const HTML_CACHE = 'public, s-maxage=300, stale-while-revalidate=86400';

const nextConfig: NextConfig = {
  output: 'standalone',
  /**
   * A34's caching, and the one thing a static marketing site has entirely in its favour.
   *
   * **Ordered least-specific FIRST, and the order is the whole correctness of this block.**
   * Next applies every entry whose `source` matches and, for one header name, the *last*
   * match wins — so the broad rule has to come before the narrow ones it would otherwise
   * undo. S21 wrote it the intuitive way round (specific first) and measured the result:
   * `/_next/static/*.css` and `/screens/*.avif` both came back `s-maxage=300` instead of
   * `immutable`, because the catch-all was overwriting them. Nothing about that is visible
   * in the config; it is only visible in a response header, which is why it was checked
   * with `curl` rather than reasoned about.
   */
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'Cache-Control', value: HTML_CACHE },
          /*
           * Two headers that are this surface's to set rather than the edge's, because both
           * are statements about the *document* and not about the connection.
           *
           * `X-Content-Type-Options` because a marketing page serves user-uploaded nothing
           * but does serve 280 images, and MIME sniffing on a public host is free to close.
           * `Referrer-Policy` because a reader following a link off this site should not
           * hand the destination the full path of the guide chapter they were reading —
           * `strict-origin-when-cross-origin` is the modern default and is stated rather
           * than assumed.
           */
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
        ],
      },
      {
        // Content-hashed build output. Next sets this itself for `/_next/static`, and it is
        // restated here because the catch-all above would otherwise override the framework's
        // own value — the policy for every immutable class is decided in one place.
        source: '/_next/static/:path*',
        headers: [{ key: 'Cache-Control', value: IMMUTABLE }],
      },
      {
        // The committed screen imagery — 280 files, 4.6 MB, and the heaviest thing the site
        // serves. Regenerated only by `npm run screens:refresh`, never per build.
        source: '/screens/:path*',
        headers: [{ key: 'Cache-Control', value: IMMUTABLE }],
      },
    ];
  },
  outputFileTracingRoot: fileURLToPath(new URL('../..', import.meta.url)),
  reactStrictMode: true,
  poweredByHeader: false,
  images: {
    formats: ['image/avif', 'image/webp'],
  },
};

export default nextConfig;
