#!/usr/bin/env bash
# =====================================================================================
# Generate the dev device CA if it is not already there (T-02).
#
#   bash infra/scripts/ensure-device-ca.sh
#
# Idempotent: it does nothing when `certs/ca_chain.crt` already exists.
#
# WHY THIS IS ITS OWN SCRIPT (Δ C124). `infra/deploy/device-ca/` is gitignored — the root key
# mints a credential for any vehicle — so it does NOT exist in a fresh checkout. EMQX bind-mounts
# the directory and reads `certs/ca_chain.crt` as the 8883 listener's `cacertfile`, and a missing
# chain does not degrade that listener: **the broker does not boot at all.**
#
# `dev-up.sh` generated this inline, so anything that brought the slim stack up WITHOUT dev-up.sh
# got no CA and no broker. `slim-verify.sh` is exactly that, which is why its EMQX checks reported
# "emqx is healthy -> <missing>" and five ACL assertions reported "refused" on every CI runner —
# there was no broker to refuse anything. It was masked for weeks behind a compose parse error that
# meant the stack never came up that far.
# =====================================================================================
set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

command -v openssl >/dev/null 2>&1 || { echo "error: openssl is required" >&2; exit 1; }

# --- Device CA for the hardware-tracker plane (C030, T-02) -----------------------------
# provisioning-svc mints per-device X.509 credentials from this CA and EMQX loads its
# `certs/ca_chain.crt` as the 8883 listener's cacertfile. It is generated HERE, before the
# stack comes up, for a hard reason: EMQX reads the file when the listener starts, and the
# listener starts long before app-services does — a broker whose cacertfile is missing does
# not degrade, it refuses to start at all.
#
# The layout is step-ca's ($STEPPATH/certs, $STEPPATH/secrets), which is what
# `StepCa:RootKeyPath` expects and what lets a real step-ca take over without moving key
# material. provisioning-svc LOADS this rather than creating it. infra/deploy/device-ca/ is
# gitignored: the root key mints a credential for any vehicle.
DEVICE_CA_DIR="$REPO_ROOT/infra/deploy/device-ca"
if [[ ! -f "$DEVICE_CA_DIR/certs/ca_chain.crt" ]]; then
  step "generating the device CA (infra/deploy/device-ca/) — T-02"
  mkdir -p "$DEVICE_CA_DIR/certs" "$DEVICE_CA_DIR/secrets"

  # ECDSA P-256 throughout: step-ca's default, and a 64-byte signature rather than 256 on
  # every handshake a 100k-tracker fleet makes. `genpkey` rather than `ecparam -genkey` because it
  # writes PKCS#8 ("BEGIN PRIVATE KEY"), which is the one format both this script and
  # provisioning-svc's own writer produce — a directory generated here and one generated by the
  # service must be loadable by the same code.
  openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 \
    -out "$DEVICE_CA_DIR/secrets/root_ca_key" 2>/dev/null
  openssl req -x509 -new -key "$DEVICE_CA_DIR/secrets/root_ca_key" -sha256 -days 3650 \
    -subj "/CN=MageRide Device Root CA" \
    -addext "basicConstraints=critical,CA:TRUE,pathlen:1" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -out "$DEVICE_CA_DIR/certs/root_ca.crt" 2>/dev/null

  openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 \
    -out "$DEVICE_CA_DIR/secrets/intermediate_ca_key" 2>/dev/null
  openssl req -new -key "$DEVICE_CA_DIR/secrets/intermediate_ca_key" \
    -subj "/CN=MageRide Device Issuing CA" -out "$DEVICE_CA_DIR/intermediate.csr" 2>/dev/null
  printf 'basicConstraints=critical,CA:TRUE,pathlen:0\nkeyUsage=critical,keyCertSign,cRLSign\n' \
    > "$DEVICE_CA_DIR/intermediate.ext"
  openssl x509 -req -in "$DEVICE_CA_DIR/intermediate.csr" \
    -CA "$DEVICE_CA_DIR/certs/root_ca.crt" -CAkey "$DEVICE_CA_DIR/secrets/root_ca_key" \
    -CAcreateserial -sha256 -days 1825 -extfile "$DEVICE_CA_DIR/intermediate.ext" \
    -out "$DEVICE_CA_DIR/certs/intermediate_ca.crt" 2>/dev/null
  rm -f "$DEVICE_CA_DIR/intermediate.csr" "$DEVICE_CA_DIR/intermediate.ext"

  # Intermediate first, root last: the bundle EMQX verifies a device leaf against.
  cat "$DEVICE_CA_DIR/certs/intermediate_ca.crt" "$DEVICE_CA_DIR/certs/root_ca.crt" \
    > "$DEVICE_CA_DIR/certs/ca_chain.crt"

  # -CAcreateserial drops a .srl beside the certificate; it is state for the next signing run and
  # not part of the CA, so it does not stay in certs/ where EMQX and the service look.
  rm -f "$DEVICE_CA_DIR/certs/root_ca.srl"

  # 0644 on the certificates: the EMQX container reads them as a different uid, and a 0600
  # cacertfile is a listener that will not start. 0600 on the keys.
  chmod 644 "$DEVICE_CA_DIR/certs/"*.crt
  chmod 600 "$DEVICE_CA_DIR/secrets/"*
fi


