'use client';

import { cx } from '@mageride/ui';

import { ScreenImage } from '@/components/ScreenImage';
import { ScreenLightbox, useLightbox, type LightboxLabels } from '@/components/showcase/ScreenLightbox';
import { SCREENS, type ScreenEntry } from '@/content/screens';
import type { Chapter } from '@/content/types';

import { Callout, type CalloutLabels } from './Callout';
import { stepId } from './ids';

/**
 * The reading column: the steps, their inline screen references, the callouts, and
 * — for exactly one chapter — the fee table.
 *
 * A client component because of the lightbox and nothing else. The steps, the
 * callouts and the table are all server-renderable content; they live here so that
 * a screen reference is a **button in the flow of a step** rather than a separate
 * gallery a reader has to correlate by hand.
 *
 * ## One lightbox, reused
 *
 * `useLightbox` + `ScreenLightbox` are the same implementation the home showcase
 * uses (S15, extracted in S17). S17's fence: *"Reuse the lightbox; do not build a
 * second one."* The set it pages through is the chapter's own screens in step
 * order, so ←/→ inside the dialog walks the chapter rather than the whole
 * registry.
 *
 * ## `table: 'daily-fee-tiers'`
 *
 * Driver chapter 13 is the fee chapter. Its six amounts live in exactly one place —
 * `DAILY_FEE_TIERS`, in minor units, asserted against the URD by
 * `test/content.test.ts` — so the chapter states the *rule* in prose and names the
 * *table* in a typed field. Rendering it here rather than special-casing the slug
 * in a page file is why a slug change cannot silently drop the six numbers.
 *
 * The currency formatting matches `FareTable` exactly, `narrowSymbol` included: the
 * same six values shown two different ways on two pages is the inconsistency S15
 * fixed, and it would come straight back if this rendered them its own way.
 */
/**
 * A chapter's prose, resolved on the server (MCS-36 D3).
 *
 * **This is the component the whole decision was about.** It renders the step text,
 * the notes and the callouts — long-form content — and it is a client component
 * because the screens open in a focus-trapped lightbox. Holding a translator here
 * meant every chapter of both guides, in both languages, was in the bundle of every
 * page on the site, including pages with no guide on them. Resolving the *current*
 * chapter on the server sends one chapter's words instead of thirty-four's.
 */
export interface ChapterBodyLabels {
  /** One "Step N" per step. */
  readonly stepLabels: readonly string[];
  /** One instruction per step. */
  readonly instructions: readonly string[];
  /** One note per step — an empty string where the step has none. */
  readonly notes: readonly string[];
  /** One "open this screen" name per step — empty where the step shows none. */
  readonly openLabels: readonly string[];
  /** One `alt` per step, for the step's screen. */
  readonly stepCaptions: readonly string[];
  readonly callouts: readonly CalloutLabels[];
  /** The fee table's caption and row labels — present only on the chapter that has one. */
  readonly feeTable?: {
    readonly caption: string;
    readonly rows: readonly { readonly label: string; readonly amount: string }[];
  };
  readonly lightbox: LightboxLabels;
}

export function ChapterBody({
  labels,
  chapter,
}: {
  readonly labels: ChapterBodyLabels;
  readonly chapter: Chapter;
}) {

  // The chapter's screens, in the order its steps refer to them, deduplicated —
  // a screen shown by two steps is one entry in the lightbox, not two.
  const referenced: ScreenEntry[] = [];
  for (const id of [...chapter.steps.map((step) => step.screenRef), ...chapter.screens]) {
    if (!id || referenced.some((entry) => entry.id === id)) continue;
    const screen = SCREENS.find((entry) => entry.id === id);
    if (screen) referenced.push(screen);
  }

  const lightbox = useLightbox(labels.lightbox.positions);

  return (
    <div className="flex flex-col gap-lg">
      <ol className="flex flex-col gap-lg">
        {chapter.steps.map((step, index) => {
          const screen = referenced.find((entry) => entry.id === step.screenRef);
          const screenIndex = screen ? referenced.indexOf(screen) : -1;

          return (
            <li key={step.instruction} id={stepId(index)} className="flex flex-col gap-xs">
              {/*
                The step number is a real element and not a `list-style`, because
                `@media print` has to keep it (S17 §3) and a marker generated by
                the list is not reliably printed. It is also the TOC's link target.
              */}
              <p className="text-body-sm font-medium text-secondary">
                {labels.stepLabels[index]}
              </p>
              <p className="text-body text-on-surface">{labels.instructions[index]}</p>
              {step.note ? (
                <p className="border-l-2 border-outline-variant pl-md text-body-sm text-on-surface-variant">
                  {labels.notes[index]}
                </p>
              ) : null}

              {screen ? (
                <button
                  type="button"
                  aria-label={labels.openLabels[index] ?? ''}
                  onClick={(event) => lightbox.open(screenIndex, event.currentTarget)}
                  className={cx(
                    'mt-xs block w-[min(100%,18rem)] rounded-card',
                    'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-secondary',
                  )}
                >
                  <ScreenImage screen={screen} alt={labels.stepCaptions[index] ?? ''} sizes="18rem" />
                </button>
              ) : null}
            </li>
          );
        })}
      </ol>

      {chapter.callouts.length > 0 ? (
        <div className="flex flex-col gap-md">
          {chapter.callouts.map((callout, index) => (
            <Callout key={callout.body} labels={labels.callouts[index]!} callout={callout} />
          ))}
        </div>
      ) : null}

      {labels.feeTable ? (
        <div className="overflow-x-auto">
          <table className="w-full min-w-[18rem] border-collapse text-left">
            <caption className="sr-only">{labels.feeTable.caption}</caption>
            <tbody>
              {labels.feeTable.rows.map((row) => (
                <tr key={row.label} className="border-b border-outline-variant">
                  <th scope="row" className="py-xs pr-md text-body font-normal text-on-surface">
                    {row.label}
                  </th>
                  <td className="py-xs text-right text-body font-medium tabular-nums text-on-surface">
                    {row.amount}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : null}

      <ScreenLightbox labels={labels.lightbox} screens={referenced} controller={lightbox} />
    </div>
  );
}
