/**
 * GENERATED by `scripts/screen-dimensions.mjs` from the committed 1x WebPs.
 * Do not edit by hand — `npm run screens:refresh` overwrites it.
 *
 * Committed on purpose: pages need explicit width/height to reserve an image's box
 * before its bytes arrive, and the plate height is **not** a constant — 416x777 and
 * 416x776 both occur among the phone frames, and there are eight distinct sizes in
 * all. See `plateSize()` in `./screens`.
 */

export interface PlateSize {
  readonly width: number;
  readonly height: number;
}

/** Keyed by `ScreenEntry.file` — the output stem, no density and no extension. */
export const SCREEN_DIMENSIONS: Readonly<Record<string, PlateSize>> = {
  'da-001-splash': { width: 416, height: 777 },
  'da-002-language-and-city': { width: 416, height: 777 },
  'da-003-phone-and-otp': { width: 416, height: 777 },
  'da-003a-driver-profile': { width: 416, height: 776 },
  'da-004-add-your-vehicle': { width: 416, height: 776 },
  'da-004a-insurance-details': { width: 416, height: 776 },
  'da-005-photograph-a-document': { width: 416, height: 776 },
  'da-006-approval-status': { width: 416, height: 777 },
  'da-007-permissions': { width: 416, height: 777 },
  'da-010-your-dashboard': { width: 416, height: 777 },
  'da-011-start-and-end-a-journey': { width: 416, height: 777 },
  'da-013-directional-travel': { width: 416, height: 776 },
  'da-014-a-new-ride-offer': { width: 416, height: 777 },
  'da-015-running-a-trip': { width: 416, height: 776 },
  'da-016a-review-a-delivery': { width: 416, height: 777 },
  'da-016b-collect-the-package': { width: 416, height: 777 },
  'da-016c-complete-the-delivery': { width: 416, height: 776 },
  'da-017-the-job-board': { width: 416, height: 776 },
  'da-018-scheduled-rides': { width: 416, height: 776 },
  'da-019-your-level-and-stats': { width: 416, height: 776 },
  'da-020-your-earnings': { width: 416, height: 777 },
  'da-021-wallet-and-daily-fee': { width: 416, height: 777 },
  'da-022-top-up-your-wallet': { width: 416, height: 777 },
  'da-023-request-credit': { width: 416, height: 776 },
  'da-024-transfer-credit': { width: 416, height: 776 },
  'da-025-fee-history': { width: 416, height: 776 },
  'da-026-my-vehicles': { width: 416, height: 777 },
  'da-027-pair-a-gps-tracker': { width: 416, height: 777 },
  'da-028-who-can-follow-you': { width: 416, height: 776 },
  'da-032-emergency-help': { width: 416, height: 777 },
  'da-033-help-and-support': { width: 416, height: 777 },
  'fp-001-fleet-sign-up': { width: 1040, height: 576 },
  'fp-002-organisation-setup': { width: 1040, height: 563 },
  'fp-002a-bank-and-payout-details': { width: 1040, height: 537 },
  'fp-003-fleet-dashboard': { width: 1040, height: 575 },
  'fp-004-onboard-a-vehicle': { width: 1040, height: 978 },
  'fp-005-assign-your-drivers': { width: 1040, height: 537 },
  'fp-006-bind-a-tracker': { width: 1040, height: 537 },
  'fp-007-live-fleet-map': { width: 1040, height: 656 },
  'fp-010-billing-and-wallet': { width: 1040, height: 537 },
  'pa-001-splash': { width: 416, height: 777 },
  'pa-002-choose-your-language': { width: 416, height: 777 },
  'pa-003-phone-and-otp': { width: 416, height: 777 },
  'pa-004-profile-setup': { width: 416, height: 776 },
  'pa-005-location-permission': { width: 416, height: 776 },
  'pa-006-mode-and-vehicle-filter': { width: 416, height: 777 },
  'pa-007-vehicle-details': { width: 416, height: 777 },
  'pa-008-search-a-place': { width: 416, height: 776 },
  'pa-009-book-a-ride': { width: 416, height: 777 },
  'pa-010-the-live-map': { width: 416, height: 777 },
  'pa-011-confirm-pickup': { width: 416, height: 777 },
  'pa-012-send-a-package': { width: 416, height: 776 },
  'pa-013-schedule-a-ride': { width: 416, height: 776 },
  'pa-014-finding-a-driver': { width: 416, height: 776 },
  'pa-015-your-ride-in-progress': { width: 416, height: 776 },
  'pa-016-payment-method': { width: 416, height: 777 },
  'pa-017-pay-the-fare': { width: 416, height: 777 },
  'pa-018-trip-summary': { width: 416, height: 777 },
  'pa-019-rate-your-driver': { width: 416, height: 777 },
  'pa-020-track-your-package': { width: 416, height: 776 },
  'pa-021-package-on-the-way': { width: 416, height: 776 },
  'pa-022-your-trips': { width: 416, height: 777 },
  'pa-024-ask-to-follow-a-vehicle': { width: 416, height: 777 },
  'pa-025-vehicles-you-follow': { width: 416, height: 776 },
  'pa-025a-subscription-payment': { width: 416, height: 776 },
  'pa-026-saved-places': { width: 416, height: 777 },
  'pa-027-profile-and-settings': { width: 416, height: 777 },
  'pa-029-emergency-help': { width: 416, height: 776 },
  'pa-030-help-and-support': { width: 416, height: 777 },
  'wt-001-tracking-link': { width: 426, height: 713 },
  'wt-002-track-without-the-app': { width: 426, height: 713 },
  'wt-003-confirm-a-pickup': { width: 426, height: 713 },
  'wt-005-package-delivered': { width: 426, height: 713 },
};
