-- =====================================================================================
-- infra/replica/seed.sql — the replica's synthetic operational data.
--
-- Run by infra/replica/seed.sh, which refuses to run against a database it did not create.
--
-- ------------------------------------------------------------------------------------
-- SYNTHETIC DATA ONLY. NEVER PRODUCTION DATA.
-- ------------------------------------------------------------------------------------
-- Every phone number is in the +9477 000 0xxx block, every name is "Replica <role> N", and every
-- registration number is in the WP-RP-xxxx series. None of it resembles a real person, which is the
-- point: this stack's edge is publicly reachable with a certificate nothing trusts.
--
-- ------------------------------------------------------------------------------------
-- WHAT THIS DOES *NOT* SEED, BECAUSE THE MIGRATIONS ALREADY DO
-- ------------------------------------------------------------------------------------
-- The C125 prompt lists "operating cities, tariffs, fee plans" among the seeder's deliverables. All
-- three are already inserted by versioned migrations and re-inserting them would either conflict or
-- silently double them:
--
--   config.operating_cities          0201__config_operating_cities.sql
--   fares.tariffs, fares.peak_windows, billing.plans,
--   billing.voucher_discount_tiers   1901__seed_fares_billing.sql
--   content, notification templates  1902-1906
--
-- seed.sh ASSERTS all of them are present and non-empty instead, and fails if they are not — a
-- replica with no tariff table prices every ride at nothing, and that is a far quieter failure than
-- a missing table.
--
-- So what is here is what no migration owns: the actors and their vehicles.
-- =====================================================================================

BEGIN;

-- -------------------------------------------------------------------------------------
-- The marker. seed.sh checks for this BEFORE running, and the whole file is idempotent, so a second
-- run changes nothing rather than doubling the fleet.
-- -------------------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS replica;

CREATE TABLE IF NOT EXISTS replica.synthetic_marker (
  marker      TEXT PRIMARY KEY,
  seeded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  note        TEXT NOT NULL
);

INSERT INTO replica.synthetic_marker (marker, note)
VALUES (
  'mageride-replica-synthetic',
  'Every row this database holds outside the versioned migrations was generated by '
  || 'infra/replica/seed.sql. If you are reading this on a machine you believe holds production '
  || 'data, something has gone very wrong.')
ON CONFLICT (marker) DO NOTHING;

-- -------------------------------------------------------------------------------------
-- Passengers. Six, one per language the platform must support twice over, because every
-- user-facing string is Si/Ta/En and a single-language replica proves nothing about the other two.
-- -------------------------------------------------------------------------------------
INSERT INTO iam.users (phone, role, first_name, language, default_payment_method)
SELECT
  '+9477000' || lpad(n::text, 4, '0'),
  'passenger',
  'Replica Passenger ' || n,
  (ARRAY['si','ta','en'])[1 + (n % 3)],
  (ARRAY['cash','onepay','lankaqr'])[1 + (n % 3)]
FROM generate_series(1, 6) AS n
ON CONFLICT (phone) DO NOTHING;

-- -------------------------------------------------------------------------------------
-- Drivers. Seven, one per daily-fee tier so D-13's rate table is exercised across the board rather
-- than at one price: Mode A free, motorbike 50, three-wheeler 100, flex 150, sedan 200, mini_van
-- 250, van 300.
-- -------------------------------------------------------------------------------------
INSERT INTO iam.users (phone, role, first_name, language, emergency_contact_name, emergency_contact_phone)
SELECT
  '+9477001' || lpad(n::text, 4, '0'),
  'driver',
  'Replica Driver ' || n,
  (ARRAY['si','ta','en'])[1 + (n % 3)],
  'Replica Next Of Kin ' || n,
  '+9477009' || lpad(n::text, 4, '0')
FROM generate_series(1, 7) AS n
ON CONFLICT (phone) DO NOTHING;

-- -------------------------------------------------------------------------------------
-- A fleet owner, for the Mode A/B vehicles and the Fleet Portal's scoping.
-- -------------------------------------------------------------------------------------
INSERT INTO iam.users (phone, email, role, first_name, language)
VALUES ('+94770020001', 'fleet@replica.invalid', 'fleet_owner', 'Replica Fleet Owner', 'en')
ON CONFLICT (phone) DO NOTHING;

-- -------------------------------------------------------------------------------------
-- Vehicles. One per driver, each of a different type, so the anti-spoof speed table (ADD §12.6),
-- the daily-fee tiers (D-13) and the query-svc type filter all see more than one value.
--
-- APPROVED deliberately: the AL-50 verification gate is a Verification Officer's decision and this
-- is the one write no route in the platform makes for a fleet vehicle — the E2E suite documents the
-- same deviation in ModeAbFleet.MarkVehicleApprovedAsync. A replica of PENDING vehicles cannot
-- dispatch a single ride.
-- -------------------------------------------------------------------------------------
WITH tiers(idx, vtype, vmode) AS (
  VALUES
    (1, 'bus',           'A'),   -- Mode A: scheduled, daily fee free
    (2, 'van',           'B'),   -- Mode B: subscription, Rs 300 tier
    (3, 'motorbike',     'C'),
    (4, 'three_wheeler', 'C'),
    (5, 'flex',          'C'),
    (6, 'sedan',         'C'),
    (7, 'mini_van',      'C')
),
drivers AS (
  SELECT id, row_number() OVER (ORDER BY phone) AS idx, first_name
  FROM iam.users
  WHERE role = 'driver' AND phone LIKE '+9477001%'
)
INSERT INTO registry.vehicles
  (owner_id, registration_number, vehicle_type, mode, status, driver_name, onboarding_status)
SELECT
  CASE WHEN t.vmode IN ('A','B')
       THEN (SELECT id FROM iam.users WHERE phone = '+94770020001')
       ELSE d.id
  END,
  'WP-RP-' || lpad(t.idx::text, 4, '0'),
  t.vtype,
  t.vmode,
  'APPROVED',
  d.first_name,
  -- 'approved', not 'complete': the CHECK on registry.vehicles.onboarding_status allows exactly
  -- 'incomplete' and 'approved' (0303).
  'approved'
FROM tiers t
JOIN drivers d ON d.idx = t.idx
ON CONFLICT DO NOTHING;

-- -------------------------------------------------------------------------------------
-- Two closed Mode A/B tracking sessions, so the replica has journey history on day one: a query
-- against an empty trips.sessions cannot tell "the read path is broken" from "nothing has happened
-- yet", which is exactly the ambiguity a demo cannot afford.
--
-- COMPLETED, not ACTIVE: D-03's partial unique index allows one ACTIVE session per driver, and
-- leaving these open would make the first real Start Journey in a smoke run collide with seed data.
-- The state vocabulary is exactly ('ACTIVE','COMPLETED') — ck_sessions_state, 0501. Not 'ENDED',
-- which is what the END of a session is called everywhere in the prose and in `end_reason`.
-- -------------------------------------------------------------------------------------
INSERT INTO trips.sessions (vehicle_id, driver_id, mode, state, started_at)
SELECT
  v.id,
  u.id,
  v.mode,
  'COMPLETED',
  now() - (interval '1 day' * v.mode_offset)
FROM (
  SELECT rv.id, rv.mode, rv.driver_name,
         CASE rv.mode WHEN 'A' THEN 2 ELSE 1 END AS mode_offset
  FROM registry.vehicles rv
  WHERE rv.registration_number LIKE 'WP-RP-%' AND rv.mode IN ('A','B')
) v
JOIN iam.users u ON u.first_name = v.driver_name AND u.role = 'driver'
WHERE NOT EXISTS (
  SELECT 1 FROM trips.sessions s WHERE s.vehicle_id = v.id
);

COMMIT;
